study:
  direction: maximize
  n_trials: 6
cross_val:
  cv: 5
  scoring: f1_macro
  random_state: 42
  verbose: 0
  n_jobs: -1
model_list: all
base_model:
  model_name: DecisionTreeClassifier
  model_score: '0.9977218621498786'
  scoring: f1_macro
