study:
  direction: maximize
  n_trials: 20

cross_validation:
  CV: 5
  scoring: accuracy
  random_state: 42


models:
  AdaBoostClassifier:
    module: sklearn.ensemble
    class: AdaBoostClassifier
    short_name: AdaBoost
    parameters:
      n_estimators:
        type: int
        min: 50
        max: 1000
      learning_rate:
        type: float
        min: 0.01
        max: 1.0
        log: true
      algorithm: "SAMME"
  RandomForestClassifier:
    module: sklearn.ensemble
    class: RandomForestClassifier
    short_name: RandomForest 
    parameters:
      n_estimators:
        type: int
        min: 50
        max: 300
      max_depth:
        type: int
        min: 2
        max: 30
      min_samples_split:
        type: int
        min: 2
        max: 20
      min_samples_leaf:
        type: int
        min: 1
        max: 20
